# # Xcode
# # Build, test, and archive an Xcode workspace on macOS.
# # Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# # https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

# trigger:
# - main

# pool:
#   vmImage: 'macos-latest'

# # - script: |
# #     sudo xcode-select -switch /Applications/Xcode_16.app/Contents/Developer
# #     xcodebuild -version
# #   displayName: 'Switch to Xcode 16'


# # - script: ls /Applications/
# #   displayName: 'List available Xcode versions'

# steps:
# - task: Xcode@5
#   inputs:
#     actions: 'build'
#     scheme: 'SwiftDemoProject'
#     sdk: 'iphoneos'
#     configuration: 'Release'
#     xcWorkspacePath: 'SwiftDemoProject.xcodeproj'
#     xcodeVersion: 'specifyPath' # Options: 11, 12, 13, 14, 15, default, specifyPath
#     xcodeDeveloperDir: '/Applications/Xcode_16.app/Contents/Developer'

# - task: InstallAppleCertificate@2
#   inputs:
#     certSecureFile: 'Certificates.p12'
#     certPwd: 'Ccare@123'

# - task: InstallAppleProvisioningProfile@1
#   inputs:
#     provisioningProfileLocation: 'secureFiles'
#     provProfileSecureFile: 'swiftdemoadco1.mobileprovision'

trigger:
- main

pool:
  vmImage: 'macos-15'

variables:
  scheme: 'SwiftDemoProject'
  sdk: 'iphoneos'
  configuration: 'Release'

steps:
# - script: |
#     sudo xcode-select -s /Applications/Xcode_16.app/Contents/Developer
#     xcodebuild -version
#   displayName: 'Switch to Xcode 16'
- script: ls /Applications/
  displayName: 'List Xcode versions'

- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'Certificates.p12'
    certPwd: 'Ccare@123'

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'swiftdemoadco1.mobileprovision'

- script: |
    xcodebuild clean -project SwiftDemoProject.xcodeproj -scheme $(scheme) -configuration $(configuration)
  displayName: 'Clean project'

- script: |
    xcodebuild build -project SwiftDemoProject.xcodeproj -scheme $(scheme) -configuration $(configuration) -sdk $(sdk)
  displayName: 'Build project'

- script: |
    xcodebuild test -project SwiftDemoProject.xcodeproj -scheme $(scheme) -destination 'platform=iOS Simulator,name=iPhone 15'
  displayName: 'Run unit/UI tests'

- script: |
    xcodebuild archive \
      -project SwiftDemoProject.xcodeproj \
      -scheme $(scheme) \
      -sdk $(sdk) \
      -configuration $(configuration) \
      -archivePath $(build.artifactstagingdirectory)/$(scheme).xcarchive
  displayName: 'Archive app'

- script: |
    xcodebuild -exportArchive \
      -archivePath $(build.artifactstagingdirectory)/$(scheme).xcarchive \
      -exportPath $(build.artifactstagingdirectory)/exportedIPA \
      -exportOptionsPlist ExportOptions.plist
  displayName: 'Export IPA'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)/exportedIPA'
    ArtifactName: 'drop'
  displayName: 'Publish IPA artifact'
